dependencies:
  # https://github.com/helm/charts/tree/master/stable/redis
  - name: redis-ha
    version: 3.0.1
    repository: https://kubernetes-charts.storage.googleapis.com
  # # https://github.com/helm/charts/tree/master/stable/traefik
  # - name: traefik
  #   version: 1.52.6
  #   repository: https://kubernetes-charts.storage.googleapis.com